### ISSUE TITLE
Check Service staus

### ISSUE THREAD

**Issue by WaleedMortaja** [elnemerahmed/OracleHelper#2]
I think you have to really check the service status instead of waiting 5 seconds and assuming that the action is done.

This may help you:
[https://stackoverflow.com/questions/178147/how-can-i-verify-if-a-windows-service-is-running](https://stackoverflow.com/questions/178147/how-can-i-verify-if-a-windows-service-is-running)

**Comment by elnemerahmed** [comment]
Thank you, but i tired it, but it always give a wrong result.
